### ISSUE TITLE
Wrong message in the creation process modal window

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/vocdoni-manager-frontend#18]
In the staging manager, when creating a csv webpoll, it appears a message saying "Send emails" that doesn't apply to this kind of voting process.

![Captura de Pantalla 2021-02-23 a les 14 59 25](https://user-images.githubusercontent.com/3515290/108855064-d917a500-75e8-11eb-9a24-65e185c1d78c.png)

**Comment by elboletaire** [comment]
@ferranrego you think I should remove steps not really in the process? Or maybe just show them grayed/disabled? 🤔

**Comment by ferranrego** [comment]
> @ferranrego you think I should remove steps not really in the process? Or maybe just show them grayed/disabled? 🤔

I think it would be better to remove this step for the csv poll as it can confuse people.
