### ISSUE TITLE
CSV Compatibility with Numbers (Mac application)

### ISSUE THREAD

**Issue by emmdim** [vocdoni/vocdoni-manager-frontend#22]
When using the Form Voting, uploading a CSV created by the Numbers Mac application using ";" as separator introduces ";;;;;"  in the first row and in the end of every data row. For example:
```
;;;;;;
Nom ;Email;ID;;;;
Name1 LastName2;mai1l@mail.com;2;;;;
Name2 LastName2;mail2@mail.com;3;;;;
```
@elboletaire  do you think it makes sense to automatically remove these characters somehow?

**Comment by elboletaire** [comment]
That's not a numbers problem, but a human error 🙃 

They started entering data on the second row; not sure we should try to fix this @emmdim
