### ISSUE TITLE
Unable to create entity/processes on the blockchain

### ISSUE THREAD

**Issue by NateWilliams2** [vocdoni/vocdoni-manager-frontend#24]
### Bug description
I'm having trouble getting an entity and processes I created on manager.stg.vocdoni.net to be registered on the blockchain.

### Steps to reproduce
- Create a new entity (https://manager.stg.vocdoni.net/entities/#/0xa76737456a15F1C700ECe7d46593262D0Caa4eC1), everything seems fine on the frontend
- Create two new processes (not webpoll) (https://manager.stg.vocdoni.net/processes/#/0xa76737456a15F1C700ECe7d46593262D0Caa4eC1/0x777f181da467d771d09305566ddcba954c30ce5a80028c6e8dce27ac5a013f65)

### Current behavior
- Neither the processes nor the entity appear on the stg explorer
- Neither the processes nor the entity appear on the api: 
```websocat wss://gw2.stg.vocdoni.net/dvote
{"id": "req-2345679","request": {"method": "getScrutinizerEntities","timestamp": 1556110671},"signature": "e8adbc699c2e2543eb8d55037102933ad8b733b98297f42e131f31aaaa8544394eba612acb29143030338b9aa115e1d870878994650b6ee0a5927ae03cd3feab01"}
{"response":{"entityIds":["26e3af30dda1f2d2cc9894817fbf1baa2e42289b","2d39f84f0e12cbeee3cb3657095d5e7adbd559f8","63c1452cf8f2fed7ead5e6c222c41e96c6ec1e0f","6de9ddb7b0ad63e9b258d9d3a92fc201a720b920","e843283dceca6a54138641e5142c823e4e17ee62","f7a702d8f197e6d510eaf740998c2029744078b5"],"ok":true,"request":"req-2345679","timestamp":1614715519},"id":"req-2345679","signature":"19d0d3f749e8c8221cfc894266a4b3ec4c77ca4d8e3e500e63f73cea97fc50063447a0289504a6bb1cadb733828b681448c6efa297375143312e83434753f2be00"}
```

```websocat wss://gw2.stg.vocdoni.net/dvote
{"id": "req-2345679","request": {"method": "getProcessList","timestamp": 1556110671, "entityId": "a76737456a15F1C700ECe7d46593262D0Caa4eC1", "fromId": ""},"signature": "e8adbc699c2e2543eb8d55037102933ad8b733b98297f42e131f31aaaa8544394eba612acb29143030338b9aa115e1d870878994650b6ee0a5927ae03cd3feab01"}
{"response":{"message":"cannot get entity process list: (Key not found)","ok":false,"request":"req-2345679","timestamp":1614715905},"id":"req-2345679","signature":"062df163305761d35573f7bb2afb4e50c7ba0befd31db496954aaa3f7316645d0d427383cd0425dd4f458d92b5adf4a88f6dfd108c2105aff46663d45f3b817101"}
```

### Expected behavior
The processes and entity should all display on the explorer + gateways. 

### Screenshots
Not sure if the "not in sync" message is important:
<img width="525" alt="Screen Shot 2021-03-02 at 2 09 03 PM" src="https://user-images.githubusercontent.com/43301705/109708671-513e1780-7b61-11eb-9e19-8ca9a3a71b4a.png">

**Comment by elboletaire** [comment]
It was an issue with a miner and/or the oracle
