### ISSUE TITLE
Add an .ico compatible with dark and light themes for the manager and webpoll

### ISSUE THREAD

**Issue by ferranrego** [vocdoni/vocdoni-manager-frontend#26]
### Bug description
Wrong .ico color in the manager and web polls when the user's browser theme is light.

### Current behavior
Now, when you are in the Vocdoni manager or in a webpoll, the .ico logo in the browser tab only appears in white. Because of this, it is only seen correctly on devices that have the dark-theme enabled.

### Expected behavior
I propose to have one .ico in white and another in black or dark. And set a dynamic system to display one or the other. So the user's will see the proper .ico in the browser tab depending on its theme.

Like this:
[Example](https://catalin.red/svg-favicon-light-dark-theme/)

### Additional context
If you agree to do it, ask me for the logos.

more info: https://medium.com/hypersphere-codes/detecting-system-theme-in-javascript-css-react-f6b961916d48

**Comment by elboletaire** [comment]
@ferranrego could you add here the logos when you can, so I have all the info at the moment of doing it? thanks :)

**Comment by ferranrego** [comment]
We can try two ways and see which looks better:

1. Use `Vocdoni Symbol` for both drak&light themes
2. Use `Vocdoni Symbol (B/W)` for light themes & `Vocdoni Symbol (B/W) -inverted-`for dark themes, detecting the type of theme dynamically.

You can find the files here:
https://www.notion.so/aragonorg/Vocdoni-s-Branding-a4ebbaf99aa94986ad7d196f8a95a8fa
